<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <EnableNUnitRunner>true</EnableNUnitRunner>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cpp2IL.JitOracle\Cpp2IL.JitOracle.csproj" />
        <ProjectReference Include="..\Cpp2IL.JitOracle.Fixtures.Valid\Cpp2IL.JitOracle.Fixtures.Valid.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
        <PackageReference Include="NUnit" Version="5.0.0-beta.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.14.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
